version: '3.8'

services:
  lunar-payments:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - lny_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
volumes:
  lny_data:
    driver: local
