services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_URL=${BASE_URL}
        - NODE_ENV=${NODE_ENV}
    ports:
      - "8081:8000"
    volumes:
      - lny_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
volumes:
  lny_data:
    driver: local
