services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - lny_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
volumes:
  lny_data:
    driver: local
